### ISSUE TITLE
[Bug]: Type error in MenuItem.d.ts

### ISSUE THREAD

**Issue by ZazzleDev** [adobe/spectrum-web-components#3587]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

MenuItem

### Expected behavior

`import type { Overlay } from '@spectrum-web-components/overlay';` in MenuItem.ts

### Actual behavior

```
node_modules/@spectrum-web-components/menu/src/MenuItem.d.ts:6:30 - error TS2307: Cannot find module 'overlay/src/Overlay.js' or its corresponding type declarations.

6 import type { Overlay } from 'overlay/src/Overlay.js';
                               ~~~~~~~~~~~~~~~~~~~~~~~~

Found 1 error in node_modules/@spectrum-web-components/menu/src/MenuItem.d.ts:6
```
https://github.com/adobe/spectrum-web-components/blob/7fc0c2e143f20ea0aa2dca3470acf7f70e068d11/packages/menu/src/MenuItem.ts#L38

@Westbrook I think this was originally introduced in https://github.com/adobe/spectrum-web-components/commit/5dfb71e5ed26cf8af83ca335a7658938f3f135a6#diff-d6c1bef5a63290802db272d6bf262beb51675b7182fe88d7d93ceda7e32650a9
See MenuItem.ts

### How can we reproduce this issue?

Run tsc on a project that depends on MenuItem
`./node_modules/.bin/tsc --noEmit`
